### ISSUE TITLE
How to Filter console output

### ISSUE THREAD

**Issue by FedeC87p** [madelson/MedallionShell#103]
0

`
I try to filter the output in console with the Medallion.Shell

`
                var command = Command.Run(
                    ffMpegBinaryPath,
                    args);
                command.RedirectTo(Console.OpenStandardOutput());
                command.RedirectFrom(Console.OpenStandardInput());
                command.RedirectStandardErrorTo(Console.OpenStandardError());
`
In this way i can't filter the output...

before I used the ProcessInfo directly, is there a way to get the same result with that library Medallion?

`
                using var FFmpegProcess = Process.Start(procStartInfo) ?? throw new InvalidOperationException("null process");

                FFmpegProcess.ErrorDataReceived += delegate (object sender, DataReceivedEventArgs received)
                {
                    if (received?.Data is not null &&
                        received.Data.StartsWith("frame=", StringComparison.InvariantCulture))
                    {
                        Console.WriteLine(received.Data);
                        Console.SetCursorPosition(0, Console.CursorTop - 1);
                    }
                };
`

**Comment by madelson** [comment]
It looks like you want to print a subset of lines from the merged stdout/stderr streams. If not, please clarify what behavior you want. If that's the case, then you can do this:

```
Command command = ...
// wrap this foreach in a Task.Run() if you want to run this logic asynchronously
foreach (var line in command.GetOutputAndErrorLines())
{
    // do any filtering/printing here
}
```

**Comment by FedeC87p** [comment]
Work, thanks for the help.

     private static CancellationTokenSource PrintConsoleStatus(Command command)

        {
            var tokenSource = new CancellationTokenSource();
            CancellationToken ct = tokenSource.Token;
            var task = Task.Run(() =>
            {
                if (ct.IsCancellationRequested)
                    return;

                foreach (var line in command.GetOutputAndErrorLines())
                {
                    if (ct.IsCancellationRequested)
                        return;

                    if (line is not null &&
                        line.StartsWith("frame=", StringComparison.InvariantCulture))
                    {
                        Console.WriteLine(line);
                        Console.SetCursorPosition(0, Console.CursorTop - 1);
                    }
                }
            }, tokenSource.Token);
            return tokenSource;
        }

**Comment by madelson** [comment]
Sounds good @FedeC87p . I've updated the README to demonstrate this approach.
