### ISSUE TITLE
Out of Memory Exception, Consuming stream and Timeout

### ISSUE THREAD

**Issue by youssefmimo** [madelson/MedallionShell#105]
When generating a large output I get an Out Of memory Exception, this can be fixed by consuming the output in a loop but doing so we loose the timeout configuration.

## Code sample

Find below the code needed to reproduce this situation. The idea is to execute a Python script that can generate a large output.

Here is the Python script : 
```python
line = ""
for i in range(99999):
  line += "~"
  print(line)
```

And the console App that executes the script  

```csharp
using Medallion.Shell;

Command commandProcess = Command.Run("python3", 
    new object[] { "script.py"},
    options => options.Timeout(TimeSpan.FromSeconds(2))
);
 
var result = await commandProcess.Task;

Console.WriteLine(result.StandardOutput);
```

Executing this code will throw an Out Of Memory Exception When trying to [allocate a new Byte array in the Pipe class](https://github.com/madelson/MedallionShell/blob/master/MedallionShell/Streams/Pipe.cs#L269). The allocate array becomes too huge.

To fix this I tried using a streaming approach I found in [a discussion about long running threads](https://github.com/madelson/MedallionShell/issues/23#issuecomment-391305492).

The code becomes as follow : 
```csharp
using Medallion.Shell;

Command commandProcess = Command.Run("python3", 
    new object[] { "script.py"},
    options => options.Timeout(TimeSpan.FromSeconds(2))
); 
 
string output = string.Empty;
string line = string.Empty;
while ((line = await commandProcess.StandardOutput.ReadLineAsync().ConfigureAwait(false)) != null)
{
    output += line; 
}

Console.WriteLine(output);

```

No more Out Of Memory but now it never times out.

## Questions 

Can someone help me understand : 
1. How can I prevent this exception ? 
2. If the only way is using the streaming approach, is there a way to correctly configure the timeout anyway ?

Thanks

**Comment by madelson** [comment]
> No more Out Of Memory but now it never times out.

Can you explain further what happens? With the code shown, I would expect it to gather lines for 2 seconds (inefficiently because we're concatenating large strings in a loop which is O(N^2)). Then the timeout should kick in and kill the process, at which point the loop would terminate and it would print the output.

What actually happens when you run it?

**Comment by youssefmimo** [comment]
It keeps running until it's completed.

I changed the range number to make it easier to run. When using the same code with a range of 10000 items (instead of 99 999) it takes 50 to 60 seconds to return, no timeout occurs. 
I tried it in Run/Debug mode and by executing the app outside of my IDE (built and run manually), same results each time.

Is there a way I can get more details/debug info on how  the timeout is behaving in this case ?

**Comment by madelson** [comment]
@YoussefAzaroual I took a crack at reproducing your test case on my end and the results I see are as expected.

Here's what I did:

In Program.cs of the process being executed:
```
StringBuilder sb = new();
for (var x = 0; x < 99999; ++x)
{
    sb.Append('~');
    Console.WriteLine(sb.ToString());
}
```

On the calling end:
```
var command = Command.Run(..., options: o => o.Timeout(TimeSpan.FromSeconds(2)));

List<string> lines = new();
string? line;
while ((line = await command.StandardOutput.ReadLineAsync().ConfigureAwait(false)) != null)
{
    lines.Add(line);
}

Console.WriteLine(lines.Count); // prints out ~20000 or so, depending on the run. Clearly not getting all the way through
await command.Task; // throws TimeoutException
```

Note that I've written this in a way that reads in all O(n^2) characters, but avoids the O(n^3) string concatenation that you're doing.

Out of curiosity, I tried changing it to use the O(n^3) approach by making these edits:
```
//List<string> lines = new();
var output = string.Empty;
...
//lines.Add(line);
output += line;
```

With this change, it runs well over a minute. **The command IS timing out** (you can see this by adding `if (command.Task.IsCompleted) { break; }` to the loop, but the concatenation is so inefficient that just processing the ~20K lines that get printed in the 2s takes a really long time.  You can repro this with a standalone example:

```
	var s = new string('~', 20000);
	var o = string.Empty;
	for (var i = 1; i <= s.Length; ++i)
	{
		o += s.Substring(0, i);
	}
```

Something to keep in mind is that the standard output pipes are buffered by the OS, so even if the command on the other side dies, the content it wrote before dying will still be there in the pipe and can be read freely.

So I think the repro is flawed, but the library is working. However, if there's a specific task you're trying to accomplish that you're still not sure how to do, I'd be happy to help!

**Comment by youssefmimo** [comment]
Thanks for looking into this and helping me better understand what was happening. 

I was aware of the performance issue of the string concatenation but not that it was such a heavy cause in the issue I was encountering. You are right the command was indeed timing out, using `if (command.Task.IsCompleted) { break; }` I was able to confirm it.

I will update my code accordingly. This issue can be closed.

**Comment by madelson** [comment]
Glad I could help! 😁
