### ISSUE TITLE
New API for Opening a File or Link in the Default Application

### ISSUE THREAD

**Issue by Bartleby2718** [madelson/MedallionShell#114]
### Context
When you're using MedallionShell, you often need to open a file or a web link. However, making this cross-platform is clunky, because [a plain `Process.Start` may not work](https://stackoverflow.com/questions/4580263/how-to-open-in-default-browser-in-c-sharp#comment113060356_4580324). We can add a new API to support this.

### Considerations
1. What should be the name of method?
  - My suggestion would be `Launch`.
    - We can be more descriptive by adding the suffix `InDefaultApplication`, but I don't think it's necessary.
  - We can also consider `Open`, but it can be misleading because there's the built-in API `File.Open`, which opens a `FileStream`. 
2. What should be the name of the parameter?
  - Some options include `pathOrUrl`, `resource`, and `target`. Not sure which would be best. 
3. Should there be a separate API for file paths vs web links?
  - Haven't tested this myself, and ChatGPT suggests that both can be handled by the same API. 
4. In which class should this new API live? 
  - Given that [the convenience methods like `Run`already live in `Command`](https://github.com/madelson/MedallionShell/blob/master/MedallionShell/Command.cs#L434), I think we can make this a `static` API in the `Command` class. It makes sense because it's a _command_ that launches something in the default application.

Given the above, my final proposal would be:
```cs
// in the `Command` class
public static void Launch(string resource);
public static Task LaunchAsync(string resource);
```

### Implementation 
https://stackoverflow.com/a/43232486 should be a good starting point.

**Comment by Bartleby2718** [comment]
@madelson Thoughts?

**Comment by madelson** [comment]
This feels like a useful function to exist somewhere, but I'm not sure I see the fit for MedallionShell/Command. The proposed APIs do not return `Command`, which makes them sort of one-off utility methods. MedallionShell is really about chaining together and manipulating processes, but this feels on the surface more like a cross-OS abstraction around opening resources (files) and having the OS take its default action.

Are you imagining this being integrated with `Command` functionality in some way?

**Comment by Bartleby2718** [comment]
Probably not.

This makes sense. Thanks for the input!
