### ISSUE TITLE
Allow RedirectStandardErrorTo StandardOutput

### ISSUE THREAD

**Issue by rocky05475** [madelson/MedallionShell#14]
Very useful feature.

**Comment by madelson** [comment]
Hi @rocky05475. Thanks for your interest in the library!

What exactly are you looking for this to do? Make the standard output stream pull from both? Or make both streams print to Console.Out of the invoking process? What should happen if both streams are outputting data simultaneously?

Can you give some additional details, a code snippet of what the feature might look like, and an example use case?

**Comment by rocky05475** [comment]
I want to do exactly what "2>&1" does in the command line prompt. Make the
standard output stream pull from both.

I wish it could be something like this:

Command.Run(...).RedirectStandardErrorToOutput();



בתאריך יום ו׳, 23 ביוני 2017 ב-15:00 מאת madelson <notifications@github.com

**Comment by madelson** [comment]
@rocky05475 one concern I have is that merging the streams on the .NET side means that the bytes could be arbitrarily interleaved due to concurrency issues.

We could combine things at the text level to ensure that whole lines are preserved, but this would behave weirdly if the program were producing raw butes or not writing output in lines.

Any thoughts on how this could be made to work?

**Comment by madelson** [comment]
@rocky05475 I think a solution for this could be a new function `GetOutputAndErrorLines()` which returns an `IEnumerable<string>` of lines from both `StandardOutput` and `StandardError`. You can then `foreach` this `IEnumerable` as the process is running:

```
foreach (var line in command.GetOutputAndErrorLines())
{
    // do something with line
}
```

**Comment by rocky05475** [comment]
Nice.

Can you add it to the library?

בתאריך יום ג׳, 27 ביוני 2017 ב-13:30 מאת madelson <notifications@github.com

**Comment by madelson** [comment]
Working on it currently. I'm going to try and wrap a few of these suggested changes into a single new release version.
