### ISSUE TITLE
How to start new Shell as administrator/root?

### ISSUE THREAD

**Issue by elyerinfox** [madelson/MedallionShell#24]
Hi There, 
This issue may be specific to my use case, but I'm looking for some assistance.   

I scoped through a bit of the code to see if I can find anything related to executing a process with either `runas` or `sudo` depending on the operating system, however was unable to find anything and cannot use the `StartInfo.Verb` property as it seems to not exist in my scope.

Do you have any suggestions for how I should go about accomplishing this?

Thanks.

**Comment by madelson** [comment]
> cannot use the StartInfo.Verb property as it seems to not exist in my scope.

You can modify arbitrary `StartInfo` properties using the `StartInfo` command option:

```
Command.Run("...", options: o => o.StartInfo(s => s.Verb = "verb"));
```

Note that this requires you to be targeting a version of .NET that supports `StartInfo.Verb` (.NET Framework or .NET Standard 2.0+).

> executing a process with either runas or sudo depending on the operating system

I'm definitely not an expert here, but I believe these are both just commands. So you could do something like:

```
Command.Run("sudo", new[] { "make", "me", "a", "sandwich" });
```

There's nothing built-in that I know of which would pick runas vs. sudo for you; you'd have to do something like switching on `Environment.OSVersion.Platform` to pick the appropriate one.

**Comment by elyerinfox** [comment]
Thanks for the speedy reply and advice, this has solved my issue.
