### ISSUE TITLE
Failing to run sudo in shell

### ISSUE THREAD

**Issue by elyerinfox** [madelson/MedallionShell#25]
Hello again,
This issue follows after #24 and I am seeking more help.

I've created a class to handle attributes that I can later specify to medallion shell in a task-manager like fashion called `comamndHolder`, and `processOptions`.  
I have a condition where if the current operating system is Linux, and the ProcessOptions has a parameter called `InvokeAsSuperuser` is true, it makes the application run as the superuser.

Unfortunately an exception is thrown explicitly stating that the command or file cannot be found with the following code and output:
```csharp
// Code
var commandHolder = new CommandHolder
    {
        Options = processOptions,
        Caller = caller,
        // MEDALLION STARTS HERE.
        Command = new Shell(
            e => e.ThrowOnError()
        ).Run("/usr/bin/sudo",
            arguments: argumentArray,
            options: o => o
                .DisposeOnExit(processOptions.DisposeOnExit)
                .WorkingDirectory(processOptions.WorkingDirectory)
        )
    };
```

```
# Output
dbug: Project.Libraries.Services.ServiceManager[0]
      OpenVPN was found: /usr/sbin/openvpn
dbug: Project.Libraries.Core.ProcessRunner.ProcessRunner[0]
      Built arugment array: /usr/sbin/openvpn /tmp/74197e20-71a9-4e70-a2b9-b5f92ac36feb.ovpn
fail: Project.Libraries.Services.ServiceManager[0]
      ACTION_FAILED
System.ComponentModel.Win32Exception (2): No such file or directory
```

If this were to be expressed in a console, I would expect  
```bash
$ /usr/bin/sudo /usr/sbin/openvpn /tmp/74197e20-71a9-4e70-a2b9-b5f92ac36feb.ovpn
```

And for my own sanity I have checked that these paths are valid.

---

By any chance would you have any idea or suggestions to test? This issue seems specific to the sudo command and passing arguments, and works inside of a normal `Process.Start()` call from my standpoint.

Regards,
Andrew H.

**Comment by madelson** [comment]
Hi Andrew,

Some thoughts:
* Make sure you are using the most recent version of `MedallionShell`
* Can you post the full `Exception.ToString()` value for the error you are hitting?
* Can you post the equivalent `Process.Start` code that runs as expected?
* If any of the arguments you are passing require quoting, you may need to override the default `CommandLineSyntax` with a linux-specific implementation (if no quoting is required it should be equivalent).
* As a debugging tool, I'd add the following code right before launching the command:
```
if (!File.Exists("/usr/bin/sudo")) { throw new Exception("could not find sudo"); }
if (!argumentsArray.Any(a => !File.Exists(a)))
{
    throw new Exception($"some argument was not a valid file: {string.Join(", ", argumentsArray)}");
}
```
* 
* Unrelated to this issue, but I just wanted to point out that you don't need to use a `Shell` here; you can specify `ThrowOnError()` as an inline option to `Command.Run` after `WorkingDirectory(...)`. The reason to use `new Shell` is to save off a re-usable set of common options with which you'll invoke several commands.

**Comment by elyerinfox** [comment]
Hi @madelson,
Thanks again for the advice and the help.

To answer your questions:
- I've confirmed that I'm using MedallionShell/1.5.1
- I've encapsulated the error and printed the exception's `ToString()` property using an ILogger:
```
fail: Project.Libraries.Core.ProcessRunner.ProcessRunner[0]
      System.ComponentModel.Win32Exception (2): No such file or directory
         at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setUser, UInt32 userId, UInt32 groupId, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean shouldThrow)
         at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
         at System.Diagnostics.Process.Start()
         at Medallion.Shell.PlatformCompatibilityHelper.SafeStart(Process process, StreamWriter& standardInput, StreamReader& standardOutput, StreamReader& standardError)
         at Medallion.Shell.ProcessCommand..ctor(ProcessStartInfo startInfo, Boolean throwOnError, Boolean disposeOnExit, TimeSpan timeout, CancellationToken cancellationToken, Encoding standardInputEncoding)
         at Medallion.Shell.Shell.Run(String executable, IEnumerable`1 arguments, Action`1 options)
         at Project.Libraries.Core.ProcessRunner.ProcessRunner.Run(ProcessOptions processOptions, IService caller) in /home/elycin/daemon/daemon/Libraries/Core/ProcessRunner/ProcessRunner.cs:line 108
fail: Project.Libraries.Services.ServiceManager[0]
      ACTION_FAILED

```

- The equivalence would be: 
```csharp
Process.Start("/usr/bin/sudo", "/usr/sbin/openvpn /tmp/74197e20-71a9-4e70-a2b9-b5f92ac36feb.ovpn")
```
- Quotes do not seem to be needed in a SSH session, I don't see why it would be needed here but will give it a go.

In regards to the shell, I will try to convert to a command and see if I get some progress.

Thanks,
Andrew H.

**Comment by madelson** [comment]
Hi Andrew,

Thanks for the additional info. 

One of the key differences between the static `Process.Start` and `Command.Run` is the `UseShellExecute` flag on `ProcessStartInfo`. UseShellExecute prevents you from redirecting stdin/stdout but has some other behaviors such as using the system path to look up the process file name. This could be the underlying issue. Please try:

```
// command, with UseShellExecute true
Command.Run(..., options: o => o.StartInfo(si => { si.UseShellExecute = true; si.RedirectStandardInput = si.RedirectStandardOutput = si.RedirectStandardError = false; }));

// process, with UseShellExecute false
var process = new Process { StartInfo = { FileName = "...", Arguments = "...", UseShellExecute = false } };
process.Start();
```

If that doesn't turn up anything, then I think the next step here is to compare the `StartInfo` objects that you are getting from `Process.Start` vs. `Command.Run`. Here's how you can do that:

```
void PrintStartInfo(ProcessStartInfo startInfo)
{
    Console.WriteLine($"FileName: '{startInfo.FileName}'");
    Console.WriteLine($"Arguments: '{startInfo.Arguments}'");
    Console.WriteLine($"UseShellExecute: '{startInfo.UseShellExecute}'");
    ... // could add more here
}

var process = Process.Start(...);
PrintStartInfo(process.StartInfo);

// for command, we need to temporarily disable DisposeOnExit so that we can inspect Command.Process
var command = Command.Run(..., options: o => o.DisposeOnExit(false));
PrintStartInfo(command.Process.StartInfo);
```

Looking at the stack trace you posted, you can see where that Win32 exception gets thrown in ForkAndExecProcess [here](https://github.com/dotnet/corefx/blob/4464cceace7615502a1003bc7488f206a47c82ee/src/Common/src/Interop/Unix/System.Native/Interop.ForkAndExecProcess.cs). The interesting thing is that a Win32Exception with no arguments gives the error "The system cannot find the file specified" on my machine, so it could be that the error message is totally erroneous in this case. Something to keep an eye out for.

**Comment by elyerinfox** [comment]
Hi, sorry for the delayed response.

I noticed that as well, a Win32 exception on a Linux environment had me puzzled at first.   
I'll be sure to try your suggestions above and get back to you as soon as possible.

Thanks,
Andrew.

**Comment by elyerinfox** [comment]
After a day of testing, i've confirmed quite a few things and had a few odd experiences.
- After changing our codebase slightly, I've confirmed that sudo is being called as I was prompted for my password:
```
dbug: Project.Libraries.Services.ServiceManager[0]
      OpenVPN init: wrote config to /tmp/12f0bee4-8117-4075-a4c1-c0fe2b6f3b88.ovpn, attempting to start 3rd party daemon.
[sudo] password for Elycin: 
dbug: Project.Libraries.Services.ServiceManager[0]
      OpenVPN was found: /usr/sbin/openvpn
dbug: Project.Libraries.Core.ProcessRunner.ProcessRunner[0]
      Built linux specific superuser argument array: /usr/sbin/openvpn /tmp/12f0bee4-8117-4075-a4c1-c0fe2b6f3b88.ovpn
fail: Project.Libraries.Services.ServiceManager[0]
      ACTION_FAILED
System.ComponentModel.Win32Exception (2): No such file or directory

```
- The command in a terminal runs as expceted:
```
[Elycin@localhost OpenVPN]$ /usr/bin/sudo /usr/sbin/openvpn /tmp/d76e2212-df58-4007-a205-977377dd1d76.ovpn 
Tue Jun 26 01:27:40 2018 WARNING: Using --management on a TCP port WITHOUT passwords is STRONGLY discouraged and considered insecure
Tue Jun 26 01:27:40 2018 OpenVPN 2.4.6 x86_64-redhat-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Apr 26 2018
Tue Jun 26 01:27:40 2018 library versions: OpenSSL 1.1.0h-fips  27 Mar 2018, LZO 2.08
Tue Jun 26 01:27:40 2018 MANAGEMENT: TCP Socket listening on [AF_INET]127.0.0.1:35100
Tue Jun 26 01:27:40 2018 NOTE: your local LAN uses the extremely common subnet address 192.168.0.x or 192.168.1.x.  Be aware that this might create routing conflicts if you connect to the VPN server from public locations such as internet cafes that use the same subnet.
Tue Jun 26 01:27:40 2018 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Tue Jun 26 01:27:40 2018 Diffie-Hellman initialized with 2048 bit key
Tue Jun 26 01:27:40 2018 TUN/TAP device tun0 opened
Tue Jun 26 01:27:40 2018 TUN/TAP TX queue length set to 100
Tue Jun 26 01:27:40 2018 do_ifconfig, tt->did_ifconfig_ipv6_setup=0
Tue Jun 26 01:27:40 2018 /sbin/ip link set dev tun0 up mtu 1500
Tue Jun 26 01:27:40 2018 /sbin/ip addr add dev tun0 172.16.224.1/24 broadcast 172.16.224.255
Tue Jun 26 01:27:40 2018 Could not determine IPv4/IPv6 protocol. Using AF_INET
Tue Jun 26 01:27:40 2018 Socket Buffers: R=[87380->87380] S=[16384->16384]
Tue Jun 26 01:27:40 2018 Listening for incoming TCP connection on [AF_INET][undef]:1194
Tue Jun 26 01:27:40 2018 TCPv4_SERVER link local (bound): [AF_INET][undef]:1194
Tue Jun 26 01:27:40 2018 TCPv4_SERVER link remote: [AF_UNSPEC]
Tue Jun 26 01:27:40 2018 MULTI: multi_init called, r=256 v=256
Tue Jun 26 01:27:40 2018 IFCONFIG POOL: base=172.16.224.2 size=252, ipv6=0
Tue Jun 26 01:27:40 2018 IFCONFIG POOL LIST
Tue Jun 26 01:27:40 2018 MULTI: TCP INIT maxclients=1024 maxevents=1028
Tue Jun 26 01:27:40 2018 Initialization Sequence Completed

```
- I am unable to run the following snippet due to it failing at the execution of `Command.Run()`, however to as far as we are programitically defining in code to be passed, they appear identical:
```
// Debugging
Console.WriteLine($"FileName: '{commandHolder.Command.Process.StartInfo.FileName}'");
Console.WriteLine($"Arguments: '{commandHolder.Command.Process.StartInfo.Arguments}'");
Console.WriteLine($"UseShellExecute: '{commandHolder.Command.Process.StartInfo.UseShellExecute}'");
```
Here's our new way of building arguments for running a command as root:
```csharp
List<string> arguments = new List<string>();
arguments.Add(processOptions.Executable);
for (var i = 0; i != processOptions.Arguments.Length; i++)
    arguments.Add(processOptions.Arguments[i] ?? "");

// Write to the console.
_logger.LogDebug("Built linux specific superuser arugment array: " + string.Join(" ", arguments));
```

I'm under the impression that at this point the problem isn't exactly `sudo` or `openvpn`.  
Do you have any more suggestions to try, or things I can hopefully provide you with?

Regards,
Andrew.

**Comment by elyerinfox** [comment]
Hello, I've obtained some more details to hopefully narrow things down.  

I've changed my `/usr/sbin/openvpn` to `/bin/iptables` and provided the `-L` flag as a dummy argument and still received the same error.

```csharp
dbug: Project.Libraries.Core.ProcessRunner.ProcessRunner[0]
      Built linux specific superuser argument array: iptables -L
fail: Project.Libraries.Services.ServiceManager[0]
      ACTION_FAILED
System.ComponentModel.Win32Exception (2): No such file or directory
   at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setUser, UInt32 userId, UInt32 groupId, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean shouldThrow)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Medallion.Shell.PlatformCompatibilityHelper.SafeStart(Process process, StreamWriter& standardInput, StreamReader& standardOutput, StreamReader& standardError)
   at Medallion.Shell.ProcessCommand..ctor(ProcessStartInfo startInfo, Boolean throwOnError, Boolean disposeOnExit, TimeSpan timeout, CancellationToken cancellationToken, Encoding standardInputEncoding)
   at Medallion.Shell.Shell.Run(String executable, IEnumerable`1 arguments, Action`1 options)
   at Project.Libraries.Core.ProcessRunner.ProcessRunner.Run(ProcessOptions processOptions, IService caller) in /home/Elycin/Project/Libraries/Core/ProcessRunner/ProcessRunner.cs:line 107
fail: Project.Libraries.Services.AutoStarter[0]
      Autostart: Processing failed for OpenVPN
      (Reason: No such file or directory)
```

**Comment by elyerinfox** [comment]
This time I have good news, and have successfully solved the problem.

My working directory was being escaped with `3rdParty\\OpenVPN` and being passed to medallion, except in my linux environment it would create a conflict as I was expecting for .NET to translate it into a friendly format using `Path.Combine()`.

Thank you for your help.

**Comment by madelson** [comment]
Thanks for the update @Elycin!
