### ISSUE TITLE
Does not throw on error for when process returns with exit code 1

### ISSUE THREAD

**Issue by elyerinfox** [madelson/MedallionShell#28]
Hello Again!

While continuing to work on the same project as my previous, I experienced a problem with iptables where due to incorrect syntax of that program's flags, medallion did not throw on error.

We wrote a simple test case to test this out with basic system commands that would respectively throw `exit 1` for windows' `powershell` and linux's `top`.

```csharp
        [Test]
        public void TestThrowOnError()
        {
            try
            {
                var cmd = Command.Run(AppConfig.isUnix ? "top" : "powershell", new[] {"--testing"}, options: o => o.ThrowOnError());
                Assert.Fail();
            }
            catch (Exception exception)
            {
                // Error means that the command execution broke. 
                Assert.Pass();
            }
        }
```

Is there a correct way to throw to the specification of ThrowOnError, or an suggestion you can provide?

Thanks,
Andrew.

**Comment by madelson** [comment]
Hi @Elycin ,

Thanks for posting. The issue here is that you are starting the command in your try block but not waiting for it to complete. 

If you call `cmd.Wait()` or `await` the command, you will observe the exception being thrown.

**Comment by elyerinfox** [comment]
Got it, thanks!
