### ISSUE TITLE
No way to set working directory

### ISSUE THREAD

**Issue by Cloudmersive** [madelson/MedallionShell#29]
Please consider adding a way to set the working directory in Command.Run

**Comment by madelson** [comment]
@Cloudmersive this is possible via the options API:

```
Command.Run("foo.exe", new[] { arg1, arg2 }, options: o => o.WorkingDirectory("directory"));
```

That said, this ought to be explicitly documented in the README. I'll add it when I next get a chance (or feel free to make a PR).
