### ISSUE TITLE
Default syntax adds unexpected quotes

### ISSUE THREAD

**Issue by Brice-xCIT** [madelson/MedallionShell#57]
Hello. I ran into an issue where I'm trying to execute a command with quotes:
```
Running: sudo -H -u root -s bash -c "apt-get update -y"
```
but the default syntax added quotes in the inner command, making it fail on Ubuntu:
```
Ran: sudo -H -u root -s bash -c "\"apt-get" update "-y\""
```
fortunately the options let me set up my own implementation of syntax (I am managing escaping myself) but the method is deprecated. Maybe it would be nice to un-deprecate it? :)

**Comment by madelson** [comment]
@Brice-xCIT  can you show how you are passing the arguments?

Each argument should be passed as a separate element to the arguments array. If you combine your arguments into one string, then the library thinks you are passing a single argument containing spaces, which must be escaped.

**Comment by Brice-xCIT** [comment]
@madelson Thank you for your reply.
The issue still occurs if I make sure to split each argument containing white-spaces into an array. (For instance breaking down `"apt-get update -y"` into `"apt-get` `update` and `-y"`. Escaping still occurs, which would be okay if it was limited to enclosing quotes. Instead it is determined to surround each whitespace-delimited argument that contains escapable character in quotes, which breaks my final bash command...
As mentionned in #58 and here above, my workaround is a custom syntax object that bypasses this rewriting. My application has its own layer above MedallionShell, that builds and escapes commands. The custom syntax class helps during this integration phase.

**Comment by madelson** [comment]
@Brice-xCIT interesting. Can you try calling it like this and seeing if that gets the expected result?

```
Command.Run("sudo", new[] { "-H", "-u", "root", "-s" "bash", "-c", "apt-get update -y" });
```

Note that I have `apt-get update -y` as one argument. The way command line escaping works is that as the caller you are passing a set of tokens to the command. By default, tokens break on whitespace, and quotes are used for escaping whenever a token needs to contain whitespace. Here, we want the sudo command to receive 7 tokens (I think) so we want to pass 7 arguments in the array.

If that doesn't work, can you post the exact code you're using to call MedallionShell for this command along with various things you've tried?

Another thing to look into would be to try and make your call with the underlying `Process` API and it's Arguments collection (just as a debugging step).

**Comment by madelson** [comment]
@Brice-xCIT any update here? Did the above suggestion work for you?

**Comment by madelson** [comment]
Closing for now; feel free to re-open if you still believe there is an issue.

**Comment by Brice-xCIT** [comment]
Hi there! Sorry for not answering earlier, I had to move on to more pressing work and could not get back to this. I still cannot really, so leaving this ticket closed is okay, I will come back to it later if I still have the issue.

This said with your explanation I think I understand my mistake was to pass the 7th token split in 3 parts. Since I manage the escaping at a higher level I will keep my current solution for now. Thanks!
