### ISSUE TITLE
This property cannot be used when attaching to already running process

### ISSUE THREAD

**Issue by danewfie** [madelson/MedallionShell#84]
Trying to use the TryAttachToProcess which does reconnect to the process and I can send kill commands to end it.
However, I am trying to recover the program outputs by using the RedirectTo and get the error:
"This property cannot be used when attaching to already running process"

Is there anything I could do to fix this or am I best at just shutting down the process gracefully after attaching to it and restarting from scratch? (not ideal solution)

```csharp
internal void Recover()
        {
            var id = File.ReadAllText(currentdir + "/RecoveryInfo.log");
            int pID;
            var valid = int.TryParse(id, out pID);
            if (valid && Command.TryAttachToProcess(pID, out cmd))
            {
                try
                {
                    cmd.RedirectTo(lines); // this line fails
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex);
                }
                Console.WriteLine("Recoverd connection");
            }
            else
            {
                Console.WriteLine("did not recover");
            }
        }
```

**Comment by madelson** [comment]
@danewfie thanks for reaching out. 

Unfortunately, I don't know of any way that a process which is not the spawning process can grab the standard input/output/error streams. Possibly this can be done with a Windows API function (if you find something let me know), but I'm not aware of it.
