### ISSUE TITLE
Please upload release tags

### ISSUE THREAD

**Issue by ForNeVeR** [madelson/MedallionShell#87]
Hello! MedallionShell is a great project (and I'm using it right now for some of my new developments).

But the first thing I see when I open this GitHub repo is "Latest release: Jul 12, 2015".
![image](https://user-images.githubusercontent.com/92793/129473867-d84b42e5-c474-46ef-8957-b08a82abe6eb.png)

This is wrong and creates a false impression that the project is abandoned and/or not published to NuGet.

To overcome this problem, please push the release tags to the Git repository (this is a good idea anyway, especially for people who are looking to reproduce their problems on the code taken from the same commit their release is), and, optionally, take a look at filling the GitHub releases for these tags (I see that you were doing this for the previous releases, but not for the ones in recent years).

**Comment by madelson** [comment]
Glad that you enjoy the library @ForNeVeR . I had moved away from doing this because I felt like NuGet provided much of the same, but you're right that this being a first impression of the repo is non-ideal. I've published the latest release as a GitHub release.
