### ISSUE TITLE
PipeTo does not work as expected

### ISSUE THREAD

**Issue by petrak-dan** [madelson/MedallionShell#88]
Hello, please advise what I am doing wrong...

While this command works on command line:
`c:\tmp\magick.exe c:\tmp\a.jpg -depth 8 ppm:- | c:\tmp\jpeg-recompress.exe --ppm - c:\tmp\b.jpg`

But in application:
```
string magickExe = @"c:\tmp\magick.exe";
string jpegRecompressExe = @"c:\tmp\jpeg-recompress.exe";
string logFile = @"c:\tmp\log.txt";
var magickArgs = new List<string>() { @"c:\tmp\a.jpg", "-depth 8", "ppm:-" };
var jpegRecompressArgs = new List<string>() { "--ppm", "-", @"c:\tmp\b.jpg" };

var command = Command.Run(magickExe, magickArgs).PipeTo(Command.Run(jpegRecompressExe, jpegRecompressArgs));
using (StreamWriter sw = File.AppendText(logFile))
{
  sw.WriteLine($"Exit code: {command.Result.ExitCode}");
  sw.WriteLine($"Stdout: {command.Result.StandardOutput}");
  sw.WriteLine($"Stderr: {command.Result.StandardError}");
}
```
Command fails and I get this output:

> Exit code: 1
> Stdout: 
> Stderr: jpeg-recompress: not a valid PPM format image!
> jpeg-recompress: invalid input file: -

Environment:

- Win10 Pro x64 21H1, Visual Studio Community 2019 16.11.0
- MedallionShell 1.6.2
- Target framework .NET 4.8
- ImageMagick binary: https://download.imagemagick.org/ImageMagick/download/binaries/ImageMagick-7.1.0-portable-Q16-HDRI-x64.zip
- jpeg-archive 2.2.0 binary: https://github.com/danielgtaylor/jpeg-archive/issues/108

Thank you!

**Comment by petrak-dan** [comment]
The problem was a space in the argument, as I learned in issue #57.
Changing this line worked:
`var magickArgs = new List<string>() { @"c:\tmp\a.jpg", "-depth", "8", "ppm:-" };`

Thanks!

**Comment by madelson** [comment]
Thanks for the update @petrak-dan !
