### ISSUE TITLE
Can't figure out what I am doin wrong

### ISSUE THREAD

**Issue by jclarkmm2** [madelson/MedallionShell#9]
I posted a question to codeducky asking what I am doing wrong. The response suggested I post my code here. I am trying to open pianobar, read the prompts in as strings and respond with commands. Ultimately I would like to use this on a embedded version. I apologize in advance, I am most comfortable 
in vb.net. 

Here is what is supposed to happen: 

![image](https://cloud.githubusercontent.com/assets/3400754/26475934/01937af6-4189-11e7-82d5-4f78804d25f4.png)

Here is what happens

![image](https://cloud.githubusercontent.com/assets/3400754/26475948/23c67ab0-4189-11e7-8e31-7e79a9abcf71.png)

As you can see I can read the output, but the write stream never seems to deliver it's it line.

I am missing some key step that is obvious to everyone but me. 

Imports System
Imports System.IO
Imports System.Diagnostics
Imports System.Threading
Imports Medallion
Imports Medallion.Shell

Module Module1

    Private PianoStart As ProcessStartInfo
    Private Piano As Medallion.Shell.Command
    Private PianoTask As Task

    Private LastMsg As String = ""
    Private WaitForInput As Boolean = False

    Private ReadStream As Medallion.Shell.Streams.ProcessStreamReader
    Private WriteStream As Medallion.Shell.Streams.ProcessStreamWriter

    Private processthrd As Thread
    Private ReadThread As Thread
    Private WriteThread As Thread

    Sub Main()
        processthrd = New Thread(AddressOf StartPiano)
        processthrd.Start()
    End Sub

    Private Sub StartPiano()
        Try

            Piano = Command.Run("""C:\Program Files (x86)\pianobar\pianobar.exe""")

            ReadStream = Piano.StandardOutput
            WriteStream = Piano.StandardInput

            WriteStream.AutoFlush = True

            ReadThread = New Thread(AddressOf ReadOutPut)
            ReadThread.Start()
            Piano.Wait()
        Catch ex As Exception
            Console.WriteLine(ex.Message)
            Console.ReadLine()
        Finally
            Piano.Kill()
        End Try

    End Sub

    Private Sub ReadOutPut()
        Dim msg As String
        While Not IsNothing(Piano)
            msg = ReadStream.ReadLine()
            If msg <> "" Then
                LastMsg = msg
                Console.WriteLine(msg)
                WriteThread = New Thread(AddressOf RespondToOutput)
                WriteThread.Start(msg)
            End If
        End While
    End Sub

    Private Sub RespondToOutput(msg As String)
        msg = Trim(msg)
        Select Case msg
            Case "[?] Email:"
                MsgBox("Address Called")
                WriteStream.Flush()
                WriteStream.WriteLine("Email@address.com" & vbCrLf)
                WriteStream.Flush()
            Case "[?] Password:"
                MsgBox("Password Called")
                WriteStream.WriteLine("password" & vbCrLf)
            Case Else
                WriteStream.WriteLine("?")
        End Select
    End Sub
End Module

**Comment by madelson** [comment]
This might be specific to pianobar. I'm having trouble getting pianobar.exe to work at all in git bash; it only seems to work in cmd. https://github.com/thedmd/pianobar-windows/issues/8 hints at this being an issue; it seems that perhaps pianobar is interacting directly with the console instead of just using stdin/stdout.

**Comment by jclarkmm2** [comment]
Interesting. That makes me raise two points. Pianobar is slightly temperamental because it only works if it has the latest TLS fingerprint. So have gotten used to compiling it myself. (There is a workaround , but I don't use it.) So obviously I can inspect the source. What should I look for to see if pianobar is bypassing standard input/output?

Pianobar normally terminates line with null characters. Which is customary in Unix. In order to get my code to see the prompts, I edited the strings to add newline characters. As is customary in windows. Is there some reason that the input is not being interpreted as finished when send CR and LF

Thanks again for your thoughts.

**Comment by madelson** [comment]
@jclarkmm2 [ui_readline.c](https://github.com/PromyLOPh/pianobar/blob/master/src/ui_readline.c) seems like the place where pianobar is processing it's standard input. It seems to do things character-by-character.

If you are already tinkering with the pianobar source, it might be nice to add some debugging statements to that file that print * flush messages to a file or to standard error (with MedallionShell you can then do `command.StandardError.PipeToAsync(Console.Error)` to capture these messages).

**Comment by jclarkmm2** [comment]
Your suggestion was exactly right. The current version of Pianobar monitors for key press events and pieces them together when it is looking for a string. That makes sense; since to control the program the user presses keys even though there isn't a prompt. However, it seems that write commands are not the same as keypress events. 

I would like to continue using the Medallion shell. But it is not obvious how to raise the key press event in the child process. Any ideas?

**Comment by madelson** [comment]
@jclarkmm2 I'm not sure how to raise keypress events for a subprocess, unfortunately. My guess is that you would need a fairly low-level API to do this (assuming it's possible).

The best bet might be to modify the pianobar source to use simple standard in/out instead of key presses.

**Comment by madelson** [comment]
@jclarkmm2 I'm going to close this for now since there don't appear to be further actions for MedallionShell at this point. Feel free to re-open if you think there's something MedallionShell could or should be doing here.
