### ISSUE TITLE
 how can i do multiple input stream?

### ISSUE THREAD

**Issue by devturks01** [madelson/MedallionShell#92]
Hello,

How can I add a 2nd input stream to the code below?

var cmdPath = @"ffmpeg.exe";
var args = "-i - -i - -map 0:v -map 1:a -y -f mp4 -";

var inputTask = cmd.StandardInput.PipeFromAsync(inputStream);
var outputTask = cmd.StandardOutput.PipeToAsync(outputStream);
var cs = new CancellationTokenSource();
var logTask = ReadError(cmd.StandardError, cs.Token);
await inputTask;
await outputTask;
cs.Cancel();
await logTask;
logTask.Wait();

please help me?

**Comment by madelson** [comment]
Hi  @devturks01 what do you mean by "2nd input stream"? Do you mean that you want to concatenate 2 streams and feed through the first one and then the second one?

**Comment by devturks01** [comment]
> Hi @devturks01 what do you mean by "2nd input stream"? Do you mean that you want to concatenate 2 streams and feed through the first one and then the second one?

yes
sample representation:
var inputTask = cmd.StandardInput.PipeFromAsync(inputStream); //video stream
var inputTask2 = cmd.StandardInput.PipeFromAsync(audioStream); //audio stream
var outputTask = cmd.StandardOutput.PipeToAsync(outputStream);

**Comment by madelson** [comment]
@devturks01 if you really want to concatenate the streams and feed one after another into standard input, you can wrap them in a custom `Stream` which does the concatenation:

```
using var concatStream = new ConcatStream(new[] { inputStream, audioStream });
var inputTask = cmd.StandardInput.PipeFromAsync(concatStream);
var outputTask = cmd.StandardOutput.PipeToAsync(outputStream);

...

class ConcatStream : Stream
{
	private readonly Stream[] _streams;
	private int _i;
	
	public ConcatStream(IEnumerable<Stream> streams)
	{
		this._streams = streams.ToArray();
	}
	
	public override bool CanRead => true;
	public override bool CanSeek => false;
	public override bool CanWrite => false;

	public override long Length => throw new NotSupportedException();
	public override long Position 
	{ 
		get => throw new NotSupportedException(); 
		set => throw new NotSupportedException(); 
	}

	public override void Flush() { }

	public override int Read(byte[] buffer, int offset, int count)
	{
		while (this._i < this._streams.Length)
		{
			var bytesRead = this._streams[this._i].Read(buffer, offset, count);
			if (bytesRead > 0) { return bytesRead; }
			++this._i;
		}
		
		return 0;
	}

	public override long Seek(long offset, SeekOrigin origin) =>
		throw new NotSupportedException();

	public override void SetLength(long value) =>
		throw new NotSupportedException();

	public override void Write(byte[] buffer, int offset, int count) =>
		throw new NotSupportedException();

	protected override void Dispose(bool disposing)
	{
		if (disposing)
		{
			foreach (var stream in this._streams) { stream.Dispose(); }
		}
	}
}
```

**Comment by devturks01** [comment]
> @devturks01 if you really want to concatenate the streams and feed one after another into standard input, you can wrap them in a custom `Stream` which does the concatenation:
> 
> ```
> using var concatStream = new ConcatStream(new[] { inputStream, audioStream });
> var inputTask = cmd.StandardInput.PipeFromAsync(concatStream);
> var outputTask = cmd.StandardOutput.PipeToAsync(outputStream);
> 
> ...
> 
> class ConcatStream : Stream
> {
> 	private readonly Stream[] _streams;
> 	private int _i;
> 	
> 	public ConcatStream(IEnumerable<Stream> streams)
> 	{
> 		this._streams = streams.ToArray();
> 	}
> 	
> 	public override bool CanRead => true;
> 	public override bool CanSeek => false;
> 	public override bool CanWrite => false;
> 
> 	public override long Length => throw new NotSupportedException();
> 	public override long Position 
> 	{ 
> 		get => throw new NotSupportedException(); 
> 		set => throw new NotSupportedException(); 
> 	}
> 
> 	public override void Flush() { }
> 
> 	public override int Read(byte[] buffer, int offset, int count)
> 	{
> 		while (this._i < this._streams.Length)
> 		{
> 			var bytesRead = this._streams[this._i].Read(buffer, offset, count);
> 			if (bytesRead > 0) { return bytesRead; }
> 			++this._i;
> 		}
> 		
> 		return 0;
> 	}
> 
> 	public override long Seek(long offset, SeekOrigin origin) =>
> 		throw new NotSupportedException();
> 
> 	public override void SetLength(long value) =>
> 		throw new NotSupportedException();
> 
> 	public override void Write(byte[] buffer, int offset, int count) =>
> 		throw new NotSupportedException();
> 
> 	protected override void Dispose(bool disposing)
> 	{
> 		if (disposing)
> 		{
> 			foreach (var stream in this._streams) { stream.Dispose(); }
> 		}
> 	}
> }
> ```

unfortunately it doesn't happen
var args = "-i - -i - -map 0:v -map 1:a -y -f mp4 -";
There are 2 pipe inputs and 1 output pipe in the parameters

**Comment by madelson** [comment]
@devturks01 processes only have 1 _standard_ input stream. I think you are looking for help with ffmpeg specifically, which is outside my area of expertise. Maybe check out something like https://superuser.com/questions/242584/how-to-provide-multiple-input-to-ffmpeg ?

If you can get your code to work on the command line and are just having trouble getting the same thing to work in MedallionShell, let me know and I can probably help.
