### ISSUE TITLE
MedallionShell memory leak

### ISSUE THREAD

**Issue by tomasr78** [madelson/MedallionShell#93]
The JB Rider profiler reports a large number of objects allocated in SOH. Do you know if this is a known issue? I may be using it wrong.

```
Small Object Heap: code that allocates a lot of memory in SOH
Allocated object type: Char[]
Last observation: 1/5/2023 7:42 AM JetBrains.Debugger.Worker64c.exe
  Allocated size: 72.1 MB
Max observation in run history: 1/5/2023 7:31 AM JetBrains.Debugger.Worker64c.exe
  Allocated size: 131.9 MB

at PlatformCompatibilityHelper.SafeStart(Process, ref StreamWriter, ref StreamReader, ref StreamReader)
at ProcessCommand..ctor(ProcessStartInfo, bool, bool, TimeSpan, CancellationToken, Encoding)
at Shell.Run(String, IEnumerable, Action)
at Command.Run(String, IEnumerable, Action)
```

` <PackageReference Include="MedallionShell" Version="1.6.2" />`

```
    public CommandResult Run(string executable, int timeout, CancellationToken cancellationToken)
    {
        var command = Command.Run(executable,
            GetCommandLine(),
            options => options
                .WorkingDirectory(FileHelper.CreateTempFolder())
                .Timeout(new TimeSpan(0, 0, 0, timeout))
                .CancellationToken(cancellationToken));
        try
        {
            command.Wait();
        }
        catch (TimeoutException)
        {
            throw new ApiException(ResponseMessageType.TimeOut);
        }

        return command.Result;
    }
```

**Comment by madelson** [comment]
@tomasr78 thanks for filing. A few questions:

* Is this a _leak_ or is it merely allocating a lot of memory? Once `Run` returns and you allow the returned `CommandResult` to be garbage collected, does the memory go back down?
* Does the executable write a lot of content to stdout/stderr? By default, MedallionShell will capture all of this content (ultimately it ends up on the `CommandResult`) which requires allocating memory to store that content. You can change this behavior if you don't want to capture the content.
* Are you able to create a standalone project which reproduces the issue? The code snippet you posted looks fine, but a lot depends on what `executable` and `GetCommandLine()` are.

**Comment by madelson** [comment]
@tomasr78 any updates here?

**Comment by tomasr78** [comment]
The program generated a large amount of error logs which resulted in SOH explosion due to stderr output. Not related to MedallionShell.
